version: '3.4'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # kafka-ui:
  #   image: provectuslabs/kafka-ui
  #   container_name: kafka-ui
  #   ports:
  #     - "5544:8080"
  #   depends_on:
  #     - kafka-broker
  #   restart: always
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka-broker:29092'
  #     KAFKA_CLUSTERS_0_ZOOKEEPER: 'zookeeper:2181'

  kowl:
    image: quay.io/cloudhut/kowl:master
    container_name: kowl
    ports:
      - "5544:8080"
    depends_on:
      - kafka-broker
    restart: always
    environment:
      KAFKA_BROKERS: 'kafka-broker:29092'

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: douglas
      POSTGRES_PASSWORD: docker
    volumes:
      - /Users/douglas.lira/workspace/docker/db/postgres:/var/lib/postgres/data

  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - 8091:80
    environment:
      PGADMIN_DEFAULT_EMAIL: douglas.vclira@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmindocker
      # PGADMIN_ENABLE_TLS: 'false'